// <auto-generated />
using Booksi.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booksi.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250103175629_Books")]
    partial class Books
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booksi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExtraPrice")
                        .HasColumnType("float");

                    b.Property<double>("ISBN")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "William L. Shirer",
                            Description = "Hitler boasted that The Third Reich would last a thousand years. It lasted only 12.\n                        But those 12 years contained some of the most catastrophic events Western civilization has ever known.\n                        No other powerful empire ever bequeathed such mountains of evidence about its birth and destruction as the Third Reich.\n                        When the bitter war was over, and before the Nazis could destroy their files, the Allied demand for unconditional surrender produced an\n                        almost hour-by-hour record of the nightmare empire built by Adolph Hitler. This record included the testimony of Nazi\n                        leaders and of concentration camp inmates, the diaries of officials, transcripts of secret conferences, army orders,\n                        private letters—all the vast paperwork behind Hitler's drive to conquer the world. \n                        The famed foreign correspondent and historian William L. Shirer, who had watched and reported on the Nazis since 1925, \n                        spent five and a half years sifting through this massive documentation. The result is a monumental study that has been widely \n                        acclaimed as the definitive record of one of the most frightening chapters in the history of mankind.\n                        This worldwide bestseller has been acclaimed as the definitive book on Nazi Germany; it is a classic work.\n                        The accounts of how the United States got involved and how Hitler used Mussolini and Japan are astonishing, and the \n                        coverage of the war-from Germany's early successes to her eventual defeat-is must reading.",
                            ExtraPrice = 80.0,
                            ISBN = 9780330700016.0,
                            Price = 100.0,
                            Title = "The Rise and Fall of the Third Reich: A History of Nazi Germany"
                        });
                });

            modelBuilder.Entity("Booksi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 0,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 0,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 0,
                            Name = "Crime"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
